### ISSUE TITLE
Job links in the UI have the wrong URL.

### ISSUE THREAD

**Issue by tmcgilchrist** [ocurrent/ocaml-multicore-ci#26]
Currently clicking on a build in the multicore UI has a URL with an extra slash.
eg 
https://multicore.ci.ocamllabs.io:8100//job/2022-05-30/213156-ci-ocluster-build-6ae122
should be 
https://multicore.ci.ocamllabs.io:8100/job/2022-05-30/213156-ci-ocluster-build-6ae122

**Comment by moyodiallo** [comment]
This issue is because of `admin-service-uri` parameter of web-ui/main.exe, in the infrastructure deployement use `https://multicore.ci.ocamllabs.io:8100/` (with slash at the end) instead of `https://multicore.ci.ocamllabs.io:8100` (without slash at the end).

I think the best way to solve that, is to delete the slash if it exists in the parameter `admin-service-uri`. Then with or without the slash, it  works.
